workflows:
  build-apk:
    name: Build APK with EAS
    environment:
      vars:
        EXPO_TOKEN: Encrypted
      node: 18.16.0
    scripts:
      - npm install -g expo-cli eas-cli
      - npm install
      - eas build --platform android --profile preview --non-interactive
    artifacts:
      - build/**/*.apk
